### ISSUE TITLE
Relaxo Logo?

### ISSUE THREAD

**Issue by apavlo** [ioquatix/relaxo#4]
I added Relaxo to my encyclopedia of databases:

https://dbdb.io/db/relaxo

Is there a logo for Relaxo that I can use?

-- Andy

**Comment by ioquatix** [comment]
@picatz do you feel like making a logo? :)

Relaxo is a mix of couchdb and github.

![unknown](https://user-images.githubusercontent.com/30030/50588793-90706f80-0ee8-11e9-89f1-7763e85501f1.png)

![unknown-1](https://user-images.githubusercontent.com/30030/50588804-9bc39b00-0ee8-11e9-9f32-079e31b9eb21.png)

Ideas?

**Comment by ioquatix** [comment]
@picatz bump.

**Comment by picatz** [comment]
![relaxo](https://user-images.githubusercontent.com/14850816/59219822-5db25d80-8b91-11e9-9eb7-f4e9b9493f8e.png)

[SVG Version as Gist](https://gist.github.com/picatz/622472d7dc25e21ad06dd1c547c6f7ee)

**Comment by apavlo** [comment]
Nice! Done:

https://dbdb.io/db/relaxo

**Comment by ioquatix** [comment]
Haha that's awesome!
